import type { Metadata } from "next";
import { FadeIn } from "@/components/ui/fade-in";
import { breadcrumbJsonLd, OG_IMAGE } from "@/lib/seo";

const title = "Privacy Policy";
const description =
  "How Shikshaloy collects, uses, and protects school, staff, student, and parent data — including our approach to data isolation, retention, and children's privacy.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/privacy" },
  openGraph: { title, description, url: "/privacy", images: [OG_IMAGE] },
  robots: { index: true, follow: true },
};

const breadcrumbs = breadcrumbJsonLd([
  { name: "Home", path: "/" },
  { name: "Privacy Policy", path: "/privacy" },
]);

const sections = [
  {
    title: "1. Information we collect",
    body: `We collect information you provide directly (school, staff, student, and parent profile details entered by a school's administrators), information generated by using the platform (attendance records, grades, fee transactions, messages), and basic technical data (login timestamps, device/browser information) needed to operate the service securely.`,
  },
  {
    title: "2. How we use it",
    body: `We use collected information to operate the platform's features (attendance, academics, fees, communication, and the other modules described on our Features page), to provide support, to secure accounts, and to improve the product. We do not sell personal data, and we do not use school or student data to train external models.`,
  },
  {
    title: "3. Children's data",
    body: `Shikshaloy is used by schools to manage student records, and many students are minors. Student data is entered and controlled by the school (the data controller); Shikshaloy acts as a processor on the school's behalf. Parents and guardians should direct requests about a student's data to their school's administration, who can manage or export it through the dashboard.`,
  },
  {
    title: "4. Data isolation and security",
    body: `Every school's data is isolated at the database level — access policies ensure staff, students, and parents can only see records belonging to their own school. Data is encrypted in transit. Access to production data by our team is limited to what's needed for support and maintenance.`,
  },
  {
    title: "5. Data sharing",
    body: `We share data with sub-processors only as needed to run the service (e.g. hosting and payment processing infrastructure), under agreements requiring them to protect it. We do not share school or student data with third parties for advertising purposes.`,
  },
  {
    title: "6. Data retention",
    body: `Data is retained for as long as a school's account is active, plus a reasonable period afterward to allow account recovery, unless a school requests earlier deletion or applicable law requires a different retention period.`,
  },
  {
    title: "7. Your rights",
    body: `Depending on your role, you can request access to, correction of, or deletion of personal data through your school's administrator, who can action most requests directly from the dashboard. You may also contact us directly using the details below.`,
  },
  {
    title: "8. Cookies & analytics",
    body: `We use essential cookies to keep you signed in and to remember basic preferences. We also use Google Analytics to understand how the platform is used and to improve it; this sets analytics cookies and shares usage data (such as pages visited and general device/location information) with Google. We do not use third-party advertising cookies or sell data to advertisers.`,
  },
  {
    title: "9. Changes to this policy",
    body: `We may update this policy as the platform evolves. Material changes will be reflected here with an updated date.`,
  },
];

export default function PrivacyPage() {
  return (
    <main className="bg-white">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }}
      />
      <section className="pt-40 pb-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <p className="text-primary-600 font-semibold text-sm uppercase tracking-widest mb-3">
              Legal
            </p>
            <h1 className="text-4xl font-extrabold text-zinc-900 tracking-tight">
              Privacy Policy
            </h1>
            <p className="mt-3 text-sm text-zinc-400">Last updated: August 2026</p>
            <p className="mt-6 text-zinc-500 leading-relaxed">
              This policy explains how Shikshaloy collects, uses, and protects
              information across our school management platform. It&apos;s written
              in plain language as a general reference — schools with specific
              regulatory or contractual requirements should have their legal
              counsel review it against those needs.
            </p>
          </FadeIn>
        </div>
      </section>

      <section className="pb-24 sm:pb-32">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 space-y-10">
          {sections.map((s) => (
            <FadeIn key={s.title}>
              <h2 className="text-lg font-semibold text-zinc-900 mb-2">{s.title}</h2>
              <p className="text-zinc-600 leading-relaxed">{s.body}</p>
            </FadeIn>
          ))}

          <FadeIn className="rounded-2xl border border-zinc-200 bg-zinc-50/60 p-6">
            <h2 className="text-lg font-semibold text-zinc-900 mb-2">Contact us</h2>
            <p className="text-zinc-600 leading-relaxed">
              Questions about this policy or a data request can be sent to{" "}
              <a href="mailto:support@shikshaloy.com" className="font-semibold text-primary-600 hover:text-primary-700">
                support@shikshaloy.com
              </a>{" "}
              or{" "}
              <a href="tel:+919932797131" className="font-semibold text-primary-600 hover:text-primary-700">
                +91 99327 97131
              </a>
              .
            </p>
          </FadeIn>
        </div>
      </section>
    </main>
  );
}
