-- Most of the demo school's original seed students were only ever given
-- name/roll/class/section/phone (from an early, shallower mock dataset) —
-- everything added to the student profile since then (admission no., DOB,
-- address, blood group, category/religion/caste, mother tongue, languages,
-- emergency contact, medical notes) was left null. Backfill it with
-- plausible demo values, guarded by coalesce() so nothing already set
-- (e.g. Amelia Eve, Ananya Banarjee, Anjali Singh, Shikshaloy Student —
-- added later with fuller data) gets overwritten.

update public.students set admission_no = coalesce(admission_no, 'ADM-2024-001'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Rajesh Sharma'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720000000'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000001'; -- Aarav Sharma
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-002'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2011-04-08'::date), present_address = coalesce(present_address, '{"line1":"Flat 102","line2":"Hill Road, Bandra West","city":"Mumbai","state":"Maharashtra","postalCode":"400050","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 102","line2":"Hill Road, Bandra West","city":"Mumbai","state":"Maharashtra","postalCode":"400050","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'A+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Telugu'), language = coalesce(language, 'English, Telugu'), emergency_contact_name = coalesce(emergency_contact_name, 'Anita Reddy'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720001327'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000011'; -- Aditya Reddy
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-003'), dob = coalesce(dob, '2016-07-15'::date), phone = coalesce(phone, '+91 9810002222'), present_address = coalesce(present_address, '{"line1":"Flat 103","line2":"Carter Road, Bandra West","city":"Mumbai","state":"Maharashtra","postalCode":"400050","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 103","line2":"Carter Road, Bandra West","city":"Mumbai","state":"Maharashtra","postalCode":"400050","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'B+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Krishnan Chauhan'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720002654'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '962cdcca-fd00-4339-ad42-8e1ebe1ef687'; -- Aman Chauhan
update public.students set medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '42f1f1ff-e3c7-4b00-a6f7-edebda438560'; -- Amelia Eve
update public.students set present_address = coalesce(present_address, '{"line1":"Flat 106","line2":"LBS Marg, Ghatkopar","city":"Mumbai","state":"Maharashtra","postalCode":"400075","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 106","line2":"LBS Marg, Ghatkopar","city":"Mumbai","state":"Maharashtra","postalCode":"400075","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'A-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Punjabi'), language = coalesce(language, 'English, Punjabi'), emergency_contact_name = coalesce(emergency_contact_name, 'Ashok Singh'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720006635'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000004'; -- Anjali Singh
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-004'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2015-07-16'::date), present_address = coalesce(present_address, '{"line1":"Flat 107","line2":"Andheri Link Road, Andheri West","city":"Mumbai","state":"Maharashtra","postalCode":"400053","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 107","line2":"Andheri Link Road, Andheri West","city":"Mumbai","state":"Maharashtra","postalCode":"400053","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'B+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Punjabi'), language = coalesce(language, 'English, Punjabi'), emergency_contact_name = coalesce(emergency_contact_name, 'Ramesh Chopra'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720007962'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000014'; -- Divya Chopra
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-005'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2014-10-23'::date), present_address = coalesce(present_address, '{"line1":"Flat 108","line2":"Powai Vihar, Powai","city":"Mumbai","state":"Maharashtra","postalCode":"400076","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 108","line2":"Powai Vihar, Powai","city":"Mumbai","state":"Maharashtra","postalCode":"400076","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'AB-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Marathi'), language = coalesce(language, 'English, Marathi'), emergency_contact_name = coalesce(emergency_contact_name, 'Usha Joshi'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720009289'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000007'; -- Karan Joshi
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-006'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2013-01-03'::date), present_address = coalesce(present_address, '{"line1":"Flat 109","line2":"Colaba Causeway, Colaba","city":"Mumbai","state":"Maharashtra","postalCode":"400001","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 109","line2":"Colaba Causeway, Colaba","city":"Mumbai","state":"Maharashtra","postalCode":"400001","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'O+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Tamil'), language = coalesce(language, 'English, Tamil'), emergency_contact_name = coalesce(emergency_contact_name, 'Sandeep Iyer'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720010616'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000012'; -- Kavya Iyer
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-007'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2012-04-10'::date), present_address = coalesce(present_address, '{"line1":"Flat 110","line2":"Bandra Kurla Complex Rd, BKC","city":"Mumbai","state":"Maharashtra","postalCode":"400051","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 110","line2":"Bandra Kurla Complex Rd, BKC","city":"Mumbai","state":"Maharashtra","postalCode":"400051","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'A+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Manoj Agarwal'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720011943'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000015'; -- Manish Agarwal
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-008'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2012-07-17'::date), present_address = coalesce(present_address, '{"line1":"Flat 111","line2":"Chembur Naka, Chembur","city":"Mumbai","state":"Maharashtra","postalCode":"400071","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 111","line2":"Chembur Naka, Chembur","city":"Mumbai","state":"Maharashtra","postalCode":"400071","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'B+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Malayalam'), language = coalesce(language, 'English, Malayalam'), emergency_contact_name = coalesce(emergency_contact_name, 'Shobha Nair'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720013270'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000008'; -- Meera Nair
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-009'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2013-10-24'::date), present_address = coalesce(present_address, '{"line1":"Flat 112","line2":"Dadar TT Circle, Dadar","city":"Mumbai","state":"Maharashtra","postalCode":"400028","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 112","line2":"Dadar TT Circle, Dadar","city":"Mumbai","state":"Maharashtra","postalCode":"400028","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'AB+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Malayalam'), language = coalesce(language, 'English, Malayalam'), emergency_contact_name = coalesce(emergency_contact_name, 'Prakash Pillai'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720014597'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000018'; -- Nisha Pillai
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-010'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2015-01-04'::date), present_address = coalesce(present_address, '{"line1":"Flat 113","line2":"Ghodbunder Road, Thane","city":"Mumbai","state":"Maharashtra","postalCode":"400615","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 113","line2":"Ghodbunder Road, Thane","city":"Mumbai","state":"Maharashtra","postalCode":"400615","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'O-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Amit Yadav'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720015924'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000010'; -- Pooja Yadav
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-011'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2011-04-11'::date), present_address = coalesce(present_address, '{"line1":"Flat 114","line2":"Sion Circle, Sion","city":"Mumbai","state":"Maharashtra","postalCode":"400022","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 114","line2":"Sion Circle, Sion","city":"Mumbai","state":"Maharashtra","postalCode":"400022","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'A-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Gujarati'), language = coalesce(language, 'English, Gujarati'), emergency_contact_name = coalesce(emergency_contact_name, 'Neelam Patel'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720017251'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000002'; -- Priya Patel
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-012'), dob = coalesce(dob, '2014-07-18'::date), phone = coalesce(phone, '+91 9810015554'), present_address = coalesce(present_address, '{"line1":"Flat 115","line2":"Malabar Hill Rd, Malabar Hill","city":"Mumbai","state":"Maharashtra","postalCode":"400006","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 115","line2":"Malabar Hill Rd, Malabar Hill","city":"Mumbai","state":"Maharashtra","postalCode":"400006","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'B+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Arun Sinha'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720018578'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '37d5c686-57e6-493d-a0ec-cd03a5685dd6'; -- Priya Sinha
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-013'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2014-10-25'::date), present_address = coalesce(present_address, '{"line1":"Flat 116","line2":"Worli Sea Face, Worli","city":"Mumbai","state":"Maharashtra","postalCode":"400018","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 116","line2":"Worli Sea Face, Worli","city":"Mumbai","state":"Maharashtra","postalCode":"400018","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'AB-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Vinod Verma'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720019905'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000013'; -- Rahul Verma
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-014'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2011-01-05'::date), present_address = coalesce(present_address, '{"line1":"Flat 117","line2":"Kandivali Station Rd, Kandivali","city":"Mumbai","state":"Maharashtra","postalCode":"400067","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 117","line2":"Kandivali Station Rd, Kandivali","city":"Mumbai","state":"Maharashtra","postalCode":"400067","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'O+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Pushpa Sen'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720021232'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000022'; -- Ritika Sen
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-015'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2015-04-12'::date), present_address = coalesce(present_address, '{"line1":"Flat 118","line2":"Borivali West, Borivali","city":"Mumbai","state":"Maharashtra","postalCode":"400092","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 118","line2":"Borivali West, Borivali","city":"Mumbai","state":"Maharashtra","postalCode":"400092","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'A+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Vinay Kumar'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720022559'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000005'; -- Rohan Kumar
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-016'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2014-07-19'::date), present_address = coalesce(present_address, '{"line1":"Flat 119","line2":"Vashi Sector 17, Navi Mumbai","city":"Mumbai","state":"Maharashtra","postalCode":"400703","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 119","line2":"Vashi Sector 17, Navi Mumbai","city":"Mumbai","state":"Maharashtra","postalCode":"400703","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'B+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Satish Mishra'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720023886'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000019'; -- Sanjay Mishra
update public.students set category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Manju Student'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720025213'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000023'; -- Shikshaloy Student
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-017'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2011-01-06'::date), present_address = coalesce(present_address, '{"line1":"Flat 101","line2":"Mulund Colony, Mulund","city":"Mumbai","state":"Maharashtra","postalCode":"400080","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 101","line2":"Mulund Colony, Mulund","city":"Mumbai","state":"Maharashtra","postalCode":"400080","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'O-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Sikhism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Punjabi'), language = coalesce(language, 'English, Punjabi'), emergency_contact_name = coalesce(emergency_contact_name, 'Suresh Kaur'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720026540'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000016'; -- Simran Kaur
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-018'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2012-04-13'::date), present_address = coalesce(present_address, '{"line1":"Flat 102","line2":"Goregaon Link Rd, Goregaon","city":"Mumbai","state":"Maharashtra","postalCode":"400062","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 102","line2":"Goregaon Link Rd, Goregaon","city":"Mumbai","state":"Maharashtra","postalCode":"400062","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'A-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Hindi'), language = coalesce(language, 'English, Hindi'), emergency_contact_name = coalesce(emergency_contact_name, 'Naresh Gupta'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720027867'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Father'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000006'; -- Sneha Gupta
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-019'), gender = coalesce(gender, 'Female'), dob = coalesce(dob, '2015-07-20'::date), present_address = coalesce(present_address, '{"line1":"Flat 103","line2":"Vikhroli Park Site, Vikhroli","city":"Mumbai","state":"Maharashtra","postalCode":"400079","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 103","line2":"Vikhroli Park Site, Vikhroli","city":"Mumbai","state":"Maharashtra","postalCode":"400079","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'B+'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Gujarati'), language = coalesce(language, 'English, Gujarati'), emergency_contact_name = coalesce(emergency_contact_name, 'Jaya Desai'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720029194'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Mother'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000020'; -- Tanvi Desai
update public.students set admission_no = coalesce(admission_no, 'ADM-2024-020'), gender = coalesce(gender, 'Male'), dob = coalesce(dob, '2012-10-27'::date), present_address = coalesce(present_address, '{"line1":"Flat 104","line2":"Santacruz East, Santacruz","city":"Mumbai","state":"Maharashtra","postalCode":"400055","country":"India"}'::jsonb), permanent_address = coalesce(permanent_address, '{"line1":"Flat 104","line2":"Santacruz East, Santacruz","city":"Mumbai","state":"Maharashtra","postalCode":"400055","country":"India"}'::jsonb), blood_group = coalesce(blood_group, 'AB-'), category = coalesce(category, 'General'), religion = coalesce(religion, 'Hinduism'), caste = coalesce(caste, 'General'), mother_tongue = coalesce(mother_tongue, 'Bengali'), language = coalesce(language, 'English, Bengali'), emergency_contact_name = coalesce(emergency_contact_name, 'Anil Bose'), emergency_contact_phone = coalesce(emergency_contact_phone, '+91 9720030521'), emergency_contact_relation = coalesce(emergency_contact_relation, 'Guardian'), medical_conditions = coalesce(medical_conditions, 'None'), allergies = coalesce(allergies, 'None') where id = '00000000-0000-0000-0003-000000000021'; -- Yash Bose

-- Refresh the demo_baseline snapshot (see 20260821132502_add_demo_flag_and_baseline_schema.sql)
-- from the now-fixed live data, so the nightly reset_demo_school() job keeps
-- this data instead of reverting to the sparse original seed. This also
-- folds in students/parents added to the live demo school after the
-- baseline was first captured (2026-08-21) — e.g. Amelia Eve, Ananya
-- Banarjee, Aman Chauhan, Priya Sinha — which the reset would otherwise
-- delete outright since they don't exist in the frozen snapshot at all.
drop table if exists demo_baseline.students;
create table demo_baseline.students as
  select * from public.students
  where school_id = '00000000-0000-0000-0000-000000000001'
    and academic_year_id = '00000000-0000-0000-0000-000000000002';

drop table if exists demo_baseline.parents;
create table demo_baseline.parents as
  select * from public.parents where school_id = '00000000-0000-0000-0000-000000000001';

drop table if exists demo_baseline.student_parents;
create table demo_baseline.student_parents as
  select sp.* from public.student_parents sp
  join demo_baseline.students s on s.id = sp.student_id;
