alter table admission_applications
  add column if not exists address              text,
  add column if not exists blood_group           text,
  add column if not exists category              text,
  add column if not exists nationality           text default 'Indian',
  add column if not exists father_name            text,
  add column if not exists father_occupation      text,
  add column if not exists father_phone           text,
  add column if not exists father_email           text,
  add column if not exists mother_name            text,
  add column if not exists mother_occupation      text,
  add column if not exists mother_phone           text,
  add column if not exists mother_email           text,
  add column if not exists guardian_name          text,
  add column if not exists guardian_relation      text,
  add column if not exists guardian_phone         text,
  add column if not exists sibling_studying       boolean default false,
  add column if not exists sibling_name           text,
  add column if not exists emergency_contact_name  text,
  add column if not exists emergency_contact_phone text;
