import type { Metadata } from "next";
import { FadeIn } from "@/components/ui/fade-in";
import { breadcrumbJsonLd, OG_IMAGE } from "@/lib/seo";

const title = "Account & Data Deletion";
const description =
  "How to request deletion of your Shikshaloy account and personal data, whether you're a school Super Admin or an individual staff, teacher, student, parent, or driver user.";

export const metadata: Metadata = {
  title,
  description,
  alternates: { canonical: "/account-deletion" },
  openGraph: { title, description, url: "/account-deletion", images: [OG_IMAGE] },
  robots: { index: true, follow: true },
};

const breadcrumbs = breadcrumbJsonLd([
  { name: "Home", path: "/" },
  { name: "Account & Data Deletion", path: "/account-deletion" },
]);

const sections = [
  {
    title: "Who this page is for",
    body: `Shikshaloy accounts are created and managed by a school (Super Admin, Admin, Staff, Teacher, Student, Parent, or Driver roles). This page explains how to delete your account and associated data, whether you're a school administrator or an individual user within a school.`,
  },
  {
    title: "If you're a Super Admin (school owner)",
    body: `You can permanently delete your school's Shikshaloy account and all associated data by contacting us at the email below from your registered school email address. We'll verify the request and process deletion within 30 days. This removes the school's records, staff, student, parent, and fee data from our systems, except where we're required to retain certain records (e.g. billing records) for legal or accounting purposes.`,
  },
  {
    title: "If you're a Staff, Teacher, Student, Parent, or Driver",
    body: `Your account is created and controlled by your school. To delete your individual account and its data, first ask your school's Super Admin or Admin to remove you from the dashboard (Dashboard → Staff/Students → remove or deactivate). If you're unable to reach your school administrator, contact us directly at the email below and we'll coordinate the deletion with your school.`,
  },
  {
    title: "What gets deleted",
    body: `Deletion removes your profile information, login credentials, and role-specific records (attendance, grades, fee history, messages) tied to your account. Data shared with or generated by other users of the same school (e.g. a teacher's grade entries for a class) is retained as part of the school's institutional records unless the school requests otherwise.`,
  },
  {
    title: "Timeline",
    body: `We process verified deletion requests within 30 days. You'll receive a confirmation email once the deletion is complete.`,
  },
];

export default function AccountDeletionPage() {
  return (
    <main className="bg-white">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbs) }}
      />
      <section className="pt-40 pb-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <FadeIn>
            <p className="text-primary-600 font-semibold text-sm uppercase tracking-widest mb-3">
              Legal
            </p>
            <h1 className="text-4xl font-extrabold text-zinc-900 tracking-tight">
              Account &amp; Data Deletion
            </h1>
            <p className="mt-3 text-sm text-zinc-400">Last updated: August 2026</p>
            <p className="mt-6 text-zinc-500 leading-relaxed">
              How to request deletion of your Shikshaloy account and personal
              data. See our{" "}
              <a href="/privacy" className="font-semibold text-primary-600 hover:text-primary-700">
                Privacy Policy
              </a>{" "}
              for details on what we collect and how it&apos;s used.
            </p>
          </FadeIn>
        </div>
      </section>

      <section className="pb-24 sm:pb-32">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 space-y-10">
          {sections.map((s) => (
            <FadeIn key={s.title}>
              <h2 className="text-lg font-semibold text-zinc-900 mb-2">{s.title}</h2>
              <p className="text-zinc-600 leading-relaxed">{s.body}</p>
            </FadeIn>
          ))}

          <FadeIn className="rounded-2xl border border-zinc-200 bg-zinc-50/60 p-6">
            <h2 className="text-lg font-semibold text-zinc-900 mb-2">Request deletion</h2>
            <p className="text-zinc-600 leading-relaxed">
              Email{" "}
              <a href="mailto:support@shikshaloy.com?subject=Account%20deletion%20request" className="font-semibold text-primary-600 hover:text-primary-700">
                support@shikshaloy.com
              </a>{" "}
              with your account details, or call{" "}
              <a href="tel:+919932797131" className="font-semibold text-primary-600 hover:text-primary-700">
                +91 99327 97131
              </a>
              .
            </p>
          </FadeIn>
        </div>
      </section>
    </main>
  );
}
